### ISSUE TITLE
Finer Missile Count Controls

### ISSUE THREAD

**Issue by CHILLYBUS** [CDarrow/DXX-Retro#110]
This mostly pertains to missile cap options -- currently, we only get uncapped, max 6, and max 2. These force a max of each secondary type to spawn on a map, so six smarts and homers and proxies, or two smarts and homers and proxies, or no cap to these (default). 1/3/4/5-caps would be much appreciated, as would controlling how many of each type of secondary (homer cap X but smart cap Y, for instance), but type control is an ancillary request to the overall numbers.

**Comment by roncli** [comment]
Duplicate #90.
