### ISSUE TITLE
Cloak MP Bug

### ISSUE THREAD

**Issue by CodeOrangelt** [CDarrow/DXX-Retro#128]
In 1.4x6 Retro multiplayer (game mode Anarchy) Cloak is permanently disabled, even if selected to be allowed in the host settings.

**Comment by roncli** [comment]
You sure about that?
![image](https://user-images.githubusercontent.com/498929/206360479-963faed7-97b5-444f-9ac3-c9a483ed5b74.png)

**Comment by CodeOrangelt** [comment]
Well damn. Me and blarget was able to replicate it multiple times. I guess it's a level fault. Ignore this.
