### ISSUE TITLE
Make Matcens Work Correctly In Coop

### ISSUE THREAD

**Issue by CDarrow** [CDarrow/DXX-Retro#29]
Like, srsly.

**Comment by vLKp** [comment]
In what way are they broken?

**Comment by CDarrow** [comment]
Ah -- my bad, I thought it was self-evident.  They sometimes don't trigger, sometimes run through an incomplete cycle, and sometimes cycle only once instead of the full three times.  It isn't deterministic as far as I can tell, and is noticeably incorrect.

**Comment by vLKp** [comment]
No problem about the ambiguity.  This is your issue tracker, so you can use it how you like. :)  I had played some cooperative missions a while back and the matcens ran at least a bit, but I never looked to see whether they behaved like they do in other game modes.  Does the problem affect both D1 and D2?  Are there any maps where it seems particularly bad?  Does it break only if there are multiple people in game or fail even if the host is alone in an open multiplayer game?

At rookie difficulty, using dxx-rebirth/dxx-rebirth@011689f038d0bb42328778dfa566211591b1d348 to play ``Descent 2: Counterstrike`` level 4, the matcen at 93:4 seems to work fine for me in both single player and in solo-cooperative.

**Comment by CDarrow** [comment]
I don't know if it affects D2.  In D1, it seems random; sometimes they work, sometimes they don't.  I haven't noticed a pattern in which ones it is.  I don't think it's even the same ones in every run, but I haven't studied the problem in detail.  I just know it's annoying when I do coop runs.

**Comment by roncli** [comment]
My observation is that matcens spawn bots MUCH more slowly in coop than in normal.

**Comment by roncli** [comment]
These should fix the issue.  I'll probably add this to 1.4X7.

1) https://github.com/dxx-rebirth/dxx-rebirth/commit/eec2fb39d655335ac9a59ee3fc3eb9d867e29e13
2) https://github.com/dxx-rebirth/dxx-rebirth/commit/6dd25cc06408857ea50ff990f9ef15ef6cab9b7b

**Comment by SiriusTR** [comment]
Commit fe0e68ca069f9265a38b5179ba8a2fad82eb96d5 should fix this. Needs testing though :)

**Comment by roncli** [comment]
Tested in D1, and things seem rather normal.
