### ISSUE TITLE
Death location fires laser lvl1 on victims respawn

### ISSUE THREAD

**Issue by icewolf-** [CDarrow/DXX-Retro#52]
When you kill an opponent and he presses primary fire to respawn, single laser lvl1 is fired from his death location.
I'm guessing it has something to do with lag,my ping is around 200.

**Comment by icewolf-** [comment]
I didn't test X1, but if you fixed it so I assume it's gone, yes?

**Comment by CDarrow** [comment]
As far as I know.  I wasn't every able to reliably reproduce it.  In theory, it would be caused by the same thing which caused the flares to do the same thing -- which I could reliably reproduce, and which I fixed.
