### ISSUE TITLE
Pilot demotion by the pilot who started the game does not send kill packet

### ISSUE THREAD

**Issue by roncli** [CDarrow/DXX-Retro#61]
I was reliably able to reproduce a scenario where a kill packet does not get sent.  If the player who is hosting the game gets demoted by getting killed, that player does not send his kill packet, resulting in scores desyncing.

See http://retro-tracker.game-server.cc/archive/game-07-09-2015-05-18-02-lagomorf-3SISTERS.html - The tracker is correct at 20-18 since Morfod hosted the game.  However, in 3 instances, he got demoted... and in all 3 instances, I did not receive the kill, resulting in a showing of 20-15.

**Comment by CDarrow** [comment]
Fixed.
