### ISSUE TITLE
Revert #77 (GoG notice removal)

### ISSUE THREAD

**Issue by roncli** [CDarrow/DXX-Retro#87]
Descent 1 and 2 are available on GoG again, so it's time to revert #77.

**Comment by roncli** [comment]
Fixed in the 1.4X7 branch.

**Comment by ryusei117** [comment]
Uh oh ... In the file `d2/INSTALL.txt`, it looks like the GOG.com notice got placed in the wrong spot. :-P Originally, it was after the sentence, "You don't own the full game, yet?" which is now on line 65 in the `1.4X7-D1` branch.
