### ISSUE TITLE
When observing, sometimes the game locks up for extended periods

### ISSUE THREAD

**Issue by roncli** [CDarrow/DXX-Retro#89]
Note that I can get this to reproduce on my test versions of 1.4X5, but only when you're free observing.  If you're following a pilot, it's 100% fine.  I'm not really sure why this happens, as all walls and objects are rendered to observers regardless whether you're following a pilot or not, why would it matter what your observer point is?

**Comment by roncli** [comment]
Cyrus and Jediluke are reporting that this is happening while PLAYING.  I've yet to see this myself, but it's only recently it started happening in 1.4X5.

I'm 90% certain it's due to a Windows 10 issue.  A recent update started it for me.  I'll look into this and see if I can't get to the bottom of it.

**Comment by CodeOrangelt** [comment]
One thing to note, multiple people are looking into this... Or at least trying to find things,  and we have found that all of the locking up happens to Windows 10 users... As far as we know at least. Maybe the issue is version incompatibility? Regardless, just trying to suggest since this post is left without reply for a long time. Dearest regards -Code

**Comment by roncli** [comment]
Code writes:

```
One thing to note, multiple people are looking into this... Or at least trying to find things, and we have found that all of the locking up happens to Windows 10 users... As far as we know at least. Maybe the issue is version incompatibility? Regardless, just trying to suggest since this post is left without reply for a long time.

Dearest regards -Code
```

**Comment by roncli** [comment]
Yeah, it's definitely the Windows 10 Fall Creator's Update.  Descent is not the only game that's fallen victim to this, so hopefully there's a bigger fix in the works from Seattle.

Blame Sirius. :)

**Comment by roncli** [comment]
Try "Disable Full Screen Options" in properties of the .exe.  I haven't tested this yet, but it is confirmed to work with Hearthstone.

![image](https://user-images.githubusercontent.com/498929/36879953-01acc5fa-1d7b-11e8-9e4b-b8a6d6e1927f.png)

**Comment by SiriusTR** [comment]
Probably also relevant: https://aka.ms/Ealw0h
I don't recall off-hand whether I've seen this. If I do I can open a bug.

**Comment by roncli** [comment]
So far the "Disable fullscreen optimizations" trick is working!  I'll be testing this on the next Observatory, because I've been missing flying around the map myself.

**Comment by ryusei117** [comment]
Oh geez, that thing ... D-: ... Yeah, when I installed the Fall Creator's Update, *almost every single one of my games* started running at an incredibly stuttery 20 FPS with horrible screen tearing. Actually, their frame rate displays still showed 60 FPS, even though everything looked choppy. (I cap most games at my display's refresh rate; it makes for very smooth video without the control lag that V-sync causes.) "Disable fullscreen optimizations" was the solution for me too. Now I do that on all of my game executables just to be sure!

**Comment by roncli** [comment]
This is pretty much nailing it for everyone, so I'm going to call this resolved.  I'll add a notice to the readme when 1.4X7 is released.
