### ISSUE TITLE
Potential object overlap issue with robots and observers in co-op

### ISSUE THREAD

**Issue by roncli** [CDarrow/DXX-Retro#96]
Currently happening in 1.4X6:

Sequence:
1) Host a co-op game in Descent First Strike level 5.  Start game as the only pilot.
2) 2nd player observes first player.
3) Host should go all the way to the yellow door and aggro the cloaked lifter.
4) Hilarity ensues.

What is happening from the observer perspective is that as long as the cloaked lifter is aggro'd, the observer's camera will rapidly switch between the host's PoV and the cloaked lifter's PoV.  Further, when the cloaked lifter is killed, the observer's camera will be bugged out for the rest of the level.

I have a feeling that there is either memory corruption or an incorrect object being addressed somewhere in the code that deals with robots in co-op.  It would be nice to find this issue and squish it since it is quite annoying for observers.

**Comment by roncli** [comment]
More on this:

1) You don't have to observe the first player.  Then, whenever the cloaked lifter is activated, you see it's PoV.  If you don't move, it's like you're observing the lifter.
2) The lifter DOES NOT ACTUALLY EXIST on the observer's end.  This leads me to believe that maybe this is less a memory corruption issue and more of an object collision issue, ie: the cloaked lifter and the observer somehow are sharing the same object.

Since this doesn't actually happen if you join the game (both players see and can interact with the cloaked lifter, and handing off ownership works like a charm), I think this may be part of a larger issue similar to #88 where hosts are not sending observers enough information about the game.  I'll play around with this idea and see if I can't figure this out.

**Comment by CDarrow** [comment]
I bet I can guess what's happening.  The observer is object 8, a spot
normally reserved for players in multi, and why a max of 7 can play in an
observed game. It wouldn't surprise me if only 4 slots are reserved for
players in coop, and object 8 is a robot. I never did test observer mode
that hard in coop.

**Comment by roncli** [comment]
Hmmm, that would make sense.  So let's make the number of starts always be 8.

roncli/DXX-Retro@66af4ff is an attempt at fixing this.  So far it's been working okay.

Incidentally, this would match the solution I suggested for the starting locations problem in #4, and also nearly matches Descent 3's behavior when it comes to spawn locations.

**Comment by roncli** [comment]
I'm going to call this fixed for now, haven't had an issue with it yet.
